package acmeConnection;
// Generated Feb 22, 2019 8:33:54 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Images generated by hbm2java
 */
public class Images  implements java.io.Serializable {


     private Integer imgId;
     private Inventory inventory;
     private String imgName;
     private String imgPath;
     private Date imgDate;

    public Images() {
    }

    public Images(Inventory inventory, String imgName, String imgPath, Date imgDate) {
       this.inventory = inventory;
       this.imgName = imgName;
       this.imgPath = imgPath;
       this.imgDate = imgDate;
    }
   
    public Integer getImgId() {
        return this.imgId;
    }
    
    public void setImgId(Integer imgId) {
        this.imgId = imgId;
    }
    public Inventory getInventory() {
        return this.inventory;
    }
    
    public void setInventory(Inventory inventory) {
        this.inventory = inventory;
    }
    public String getImgName() {
        return this.imgName;
    }
    
    public void setImgName(String imgName) {
        this.imgName = imgName;
    }
    public String getImgPath() {
        return this.imgPath;
    }
    
    public void setImgPath(String imgPath) {
        this.imgPath = imgPath;
    }
    public Date getImgDate() {
        return this.imgDate;
    }
    
    public void setImgDate(Date imgDate) {
        this.imgDate = imgDate;
    }




}


